name: CI default

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build-and-maybe-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          file: ./ConfigServerProxy/Dockerfile
          push: false
          load: true
          tags: davidkvc/config-server-proxy:latest

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF_NAME#v}
          docker tag davidkvc/config-server-proxy:latest davidkvc/config-server-proxy:$TAG
          docker push davidkvc/config-server-proxy:$TAG
          docker push davidkvc/config-server-proxy:latest
